function createLmenu(){

var iLmenu=''
+'		<div class="sidebar-menu-inner ps-container ps-active-y">'
+'			'
+'			<header class="logo-env">'
+''
+'				<!-- logo -->'
+'				<div class="logo">'
+'					<a href="index.html">'
+'						<img src="assets/images/logo@2x.png" width="120" alt="" />'
+'					</a>'
+'				</div>'
+''
+'				<!-- logo collapse icon -->'
+'				<div class="sidebar-collapse">'
+'					<a href="#" class="sidebar-collapse-icon"><!-- add class "with-animation" if you want sidebar to have animation during expanding/collapsing transition -->'
+'						<i class="entypo-menu"></i>'
+'					</a>'
+'				</div>'
+''
+'								'
+'				<!-- open/close menu icon (do not remove if you want to enable menu on mobile devices) -->'
+'				<div class="sidebar-mobile-menu visible-xs">'
+'					<a href="#" class="with-animation"><!-- add class "with-animation" to support animation -->'
+'						<i class="entypo-menu"></i>'
+'					</a>'
+'				</div>'
+''
+'			</header>'
+'			'
+'									'
+'			<ul id="main-menu" class="main-menu">'
+'				<!-- add class "multiple-expanded" to allow multiple submenus to open -->'
+'				<!-- class "auto-inherit-active-class" will automatically add "active" class for parent elements who are marked already with class "active" -->'
+'				<li class="opened">'
+'					<a href="#">'
+'						<i class="entypo-monitor"></i>'
+'						<span class="title"> # Atendimentos</span>'
+'					</a>'
+'					<ul class="">'
+'						<li class="active">'
+'							<a href="chrome-extension://dehheadpmhimcoldleepicbogjngiikh/Vweb/painel.html">'
+'								<span class="title">Atendimento</span>'
+'							</a>'
+'						</li>'
+''
+''
+'						<li>'
+'							<a href="chrome-extension://dehheadpmhimcoldleepicbogjngiikh/Vweb/default.html">'
+'								<span class="title">Histórico</span>'
+'							</a>'
+'						</li>'
+''
+''
+'						<li>'
+'							<a href="chrome-extension://dehheadpmhimcoldleepicbogjngiikh/Vweb/retorno_operador.html">'
+'								<span class="title">Fila de Retorno</span>'
+'							</a>'
+'						</li>'
+''
+'					</ul>'
+'				</li>'
+'				<li class="root-level"> <a href="#" target="">'
+'					<i class="entypo-chart-bar"></i>'
+'					<span class="title">Meus Indicadores</span></a> '
+'				</li>'
+'				<li class="root-level"> <a href="#" target="">'
+'					<i class="glyphicon glyphicon-wrench"></i>'
+'					<span class="title">Ferramentas</span></a> '
+'				</li>'
+'				<li class="root-level"> <a href="#" target="">'
+'					<i class="entypo-globe"></i>'
+'					<span class="title">Social</span></a> '
+'				</li>'
+'				<li class="root-level"> <a href="chrome-extension://dehheadpmhimcoldleepicbogjngiikh/Vweb/options.html" target="_blank">'
+'					<i class="entypo-cog"></i>'
+'					<span class="title">Opções</span></a> '
+'				</li>'
+'				'
+'				<li>'
+'					<a href="#">'
+'						<i class="entypo-layout"></i>'
+'						<span class="title">Histórico de Atualizações</span>'
+'					</a>'
+'					<ul>'
+'						<li>'
+'							<a href="chrome-extension://dehheadpmhimcoldleepicbogjngiikh/Vweb/default.html">'
+'								<span class="title">Novidades</span>'
+'								<span class="badge badge-success badge-roundless">Em breve</span>'
+'							</a>'
+'						</li>'
+'						'
+'					</ul>'
+'				</li>'
+'				'
+'			</ul>'
+'			'
+'		</div>';
document.getElementById('vsmlmenu').innerHTML=iLmenu;
}
createLmenu();
//window.addEventListener("load", createLmenu); 
/* FUNÇÃO QUE VAI CAPTURAR V5ID E 248 IP  */
